apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: anyscale-operator  
spec:
  serviceAccountName: anyscale-operator
  restartPolicy: Never
  volumes:
    - name: azure-blob
      persistentVolumeClaim:
        claimName: anyscale-shared-fuse
  containers:
    - name: cuda-container
      image: nvidia/cuda:12.4.0-base-ubuntu22.04
      command: ["/bin/sh"]
      args: ["-c","sleep 1000"]
      volumeMounts:
        - name: azure-blob
          mountPath: /mnt/cloud-storage
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
        requests:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  - key: gpu-type
    operator: Equal
    value: a100
    effect: NoSchedule
  - key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
    effect: NoSchedule